<?php
/**
 * This creates a sitemap file for all DisplayCase installations by crawling curated list of
 * their backend Google Sheets for their tab names; it will ignore "example" and any starting
 * with "!!" characters.
 * 
 * IMPORTANT: This code was generated by AI "GPT-5.6 Sol (High)" and amended only lightly.
 *
 * PHP version 8
 *
 * @category   LIBWebApplication
 * @package    DisplayCaseSitemap
 * @author     Steven Orr <sorr@mail.fresnostate.edu>
 * @copyright  2026 Fresno State Library, Fresno State 
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU Public License v3
 * @link       https://github.com/fresnostate-library/displaycase_sitemap
*/

declare(strict_types=1);

/**
 * Build an XML sitemap from the tab names in one or more Google Sheets,
 * excluding any tab whose title is exactly "example" or begins with "!!".
 *
 * 1) Place this file beside configuration.php outside the webroot. 
 * 2) Set app.fullPathToFile to the complete absolute path of the sitemap file, for example:
 *
 *     'fullPathToFile' => '/var/www/html/displaycase/sitemap.xml'
 *
 * 3) Then run:
 *
 *     php generate_sitemap.php
 */

const GOOGLE_SHEETS_API_URL = 'https://sheets.googleapis.com/v4/spreadsheets/';
const SITEMAP_NAMESPACE = 'http://www.sitemaps.org/schemas/sitemap/0.9';
const MAX_SITEMAP_URLS = 50000;

try {
    $configuration = loadConfiguration(__DIR__ . '/configuration.php');
    $settings = validateConfiguration($configuration);

    $urls = [];

    foreach ($settings['sheets'] as $sheet) {
        $tabNames = fetchTabNames(
            $sheet['googleSheetId'],
            $settings['googleApiKey'],
            $sheet['owner']
        );

        foreach ($tabNames as $tabName) {
            if ($tabName === 'example' || str_starts_with($tabName, '!!')) {
                continue;
            }

            // Treat the complete tab name as one URL path segment. For example,
            // "Fall 2026" becomes "Fall%202026" and "A/B" becomes "A%2FB".
            $url = rtrim($sheet['baseUrl'], '/') . '/' . rawurlencode($tabName);
            $urls[$url] = true;
        }
    }

    $locations = array_keys($urls);

    if (count($locations) > MAX_SITEMAP_URLS) {
        throw new RuntimeException(
            sprintf(
                'The sitemap contains %d URLs; a sitemap may contain at most %d.',
                count($locations),
                MAX_SITEMAP_URLS
            )
        );
    }

    $xml = createSitemapXml($locations);
    $outputPath = resolveOutputPath($settings['fullPathToFile']);

    writeSitemap($outputPath, $xml);
    respond(sprintf('Created %s with %d URL(s).', $outputPath, count($locations)));
} catch (Throwable $exception) {
    respond('Sitemap generation failed: ' . $exception->getMessage(), true);
    exit(1);
}

/**
 * @return array<string, mixed>
 */
function loadConfiguration(string $path): array
{
    if (!is_file($path) || !is_readable($path)) {
        throw new RuntimeException('The configuration file is missing or unreadable: ' . $path);
    }

    $configuration = require $path;

    if (!is_array($configuration)) {
        throw new RuntimeException('configuration.php must return an array.');
    }

    return $configuration;
}

/**
 * @param array<string, mixed> $configuration
 * @return array{
 *     googleApiKey: string,
 *     fullPathToFile: string,
 *     sheets: list<array{owner: string, googleSheetId: string, baseUrl: string}>
 * }
 */
function validateConfiguration(array $configuration): array
{
    $app = $configuration['app'] ?? null;
    $sheetData = $configuration['sheetData'] ?? null;

    if (!is_array($app)) {
        throw new RuntimeException('The configuration must contain an app array.');
    }

    if (!is_array($sheetData) || $sheetData === []) {
        throw new RuntimeException('The configuration must contain at least one sheetData entry.');
    }

    $googleApiKey = requireNonEmptyString($app, 'googleApiKey', 'app');
    $fullPathToFile = requireNonEmptyString($app, 'fullPathToFile', 'app');

    if (!isAbsolutePath($fullPathToFile)) {
        throw new RuntimeException('app.fullPathToFile must be an absolute filesystem path.');
    }

    if (strtolower((string) pathinfo($fullPathToFile, PATHINFO_EXTENSION)) !== 'xml') {
        throw new RuntimeException('app.fullPathToFile must identify an XML file.');
    }

    $sheets = [];

    foreach ($sheetData as $index => $entry) {
        if (!is_array($entry)) {
            throw new RuntimeException(sprintf('sheetData[%s] must be an array.', (string) $index));
        }

        // The supplied configuration uses: [owner, googleSheetId, baseUrl].
        $owner = $entry['owner'] ?? $entry[0] ?? null;
        $googleSheetId = $entry['googleSheetId'] ?? $entry[1] ?? null;
        $baseUrl = $entry['baseUrl'] ?? $entry[2] ?? null;

        foreach (
            [
                'owner' => $owner,
                'googleSheetId' => $googleSheetId,
                'baseUrl' => $baseUrl,
            ] as $field => $value
        ) {
            if (!is_string($value) || trim($value) === '') {
                throw new RuntimeException(
                    sprintf('sheetData[%s].%s must be a non-empty string.', (string) $index, $field)
                );
            }
        }

        $baseUrl = trim($baseUrl);

        if (filter_var($baseUrl, FILTER_VALIDATE_URL) === false) {
            throw new RuntimeException(
                sprintf('sheetData[%s].baseUrl is not a valid absolute URL.', (string) $index)
            );
        }

        $scheme = strtolower((string) parse_url($baseUrl, PHP_URL_SCHEME));

        if (!in_array($scheme, ['http', 'https'], true)) {
            throw new RuntimeException(
                sprintf('sheetData[%s].baseUrl must use HTTP or HTTPS.', (string) $index)
            );
        }

        $sheets[] = [
            'owner' => trim($owner),
            'googleSheetId' => trim($googleSheetId),
            'baseUrl' => $baseUrl,
        ];
    }

    return [
        'googleApiKey' => $googleApiKey,
        'fullPathToFile' => $fullPathToFile,
        'sheets' => $sheets,
    ];
}

function isAbsolutePath(string $path): bool
{
    if ($path === '') {
        return false;
    }

    if (DIRECTORY_SEPARATOR === '\\') {
        return preg_match('/^(?:[A-Za-z]:[\/\\\\]|\\\\\\\\)/', $path) === 1;
    }

    return str_starts_with($path, '/');
}

/**
 * @param array<string, mixed> $values
 */
function requireNonEmptyString(array $values, string $key, string $section): string
{
    $value = requireString($values, $key, $section);

    if (trim($value) === '') {
        throw new RuntimeException(sprintf('%s.%s must not be empty.', $section, $key));
    }

    return trim($value);
}

/**
 * @param array<string, mixed> $values
 */
function requireString(array $values, string $key, string $section): string
{
    if (!array_key_exists($key, $values) || !is_string($values[$key])) {
        throw new RuntimeException(sprintf('%s.%s must be a string.', $section, $key));
    }

    return $values[$key];
}

/**
 * @return list<string>
 */
function fetchTabNames(string $spreadsheetId, string $apiKey, string $owner): array
{
    if (!function_exists('curl_init')) {
        throw new RuntimeException('The PHP cURL extension is required.');
    }

    $requestUrl = GOOGLE_SHEETS_API_URL
        . rawurlencode($spreadsheetId)
        . '?'
        . http_build_query(
            [
                'fields' => 'sheets.properties.title',
                'key' => $apiKey,
            ],
            '',
            '&',
            PHP_QUERY_RFC3986
        );

    $curl = curl_init($requestUrl);

    if ($curl === false) {
        throw new RuntimeException(sprintf('Could not initialize the Google API request for "%s".', $owner));
    }

    curl_setopt_array(
        $curl,
        [
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_FOLLOWLOCATION => false,
            CURLOPT_CONNECTTIMEOUT => 10,
            CURLOPT_TIMEOUT => 30,
            CURLOPT_HTTPHEADER => ['Accept: application/json'],
            CURLOPT_USERAGENT => 'DisplayCase-Sitemap-Generator/1.0',
        ]
    );

    $response = curl_exec($curl);
    $curlError = curl_error($curl);
    $statusCode = (int) curl_getinfo($curl, CURLINFO_RESPONSE_CODE);
    curl_close($curl);

    if ($response === false) {
        throw new RuntimeException(
            sprintf('The Google API request for "%s" failed: %s', $owner, $curlError)
        );
    }

    try {
        $payload = json_decode($response, true, 512, JSON_THROW_ON_ERROR);
    } catch (JsonException $exception) {
        throw new RuntimeException(
            sprintf('Google returned invalid JSON for "%s".', $owner),
            0,
            $exception
        );
    }

    if ($statusCode < 200 || $statusCode >= 300) {
        $apiMessage = is_array($payload)
            ? ($payload['error']['message'] ?? 'No error details were returned.')
            : 'No error details were returned.';

        throw new RuntimeException(
            sprintf('Google API error for "%s" (HTTP %d): %s', $owner, $statusCode, $apiMessage)
        );
    }

    if (!is_array($payload) || !isset($payload['sheets']) || !is_array($payload['sheets'])) {
        throw new RuntimeException(sprintf('Google returned no sheet metadata for "%s".', $owner));
    }

    $tabNames = [];

    foreach ($payload['sheets'] as $sheet) {
        $title = $sheet['properties']['title'] ?? null;

        if (!is_string($title) || $title === '') {
            throw new RuntimeException(sprintf('Google returned an invalid tab title for "%s".', $owner));
        }

        $tabNames[] = $title;
    }

    return $tabNames;
}

/**
 * @param list<string> $locations
 */
function createSitemapXml(array $locations): string
{
    $lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<urlset xmlns="' . SITEMAP_NAMESPACE . '">',
    ];

    foreach ($locations as $location) {
        $escapedLocation = htmlspecialchars($location, ENT_QUOTES | ENT_XML1, 'UTF-8');
        $lines[] = '  <url>';
        $lines[] = '    <loc>' . $escapedLocation . '</loc>';
        $lines[] = '  </url>';
    }

    $lines[] = '</urlset>';

    return implode("\n", $lines) . "\n";
}

function resolveOutputPath(string $fullPathToFile): string
{
    $directory = dirname($fullPathToFile);
    $resolvedDirectory = realpath($directory);

    if ($resolvedDirectory === false || !is_dir($resolvedDirectory)) {
        throw new RuntimeException('The sitemap output directory does not exist: ' . $directory);
    }

    if (!is_writable($resolvedDirectory)) {
        throw new RuntimeException('The sitemap output directory is not writable: ' . $resolvedDirectory);
    }

    if (is_dir($fullPathToFile)) {
        throw new RuntimeException('app.fullPathToFile identifies a directory, not a file.');
    }

    if (file_exists($fullPathToFile) && !is_writable($fullPathToFile)) {
        throw new RuntimeException('The sitemap file is not writable: ' . $fullPathToFile);
    }

    return $resolvedDirectory . DIRECTORY_SEPARATOR . basename($fullPathToFile);
}

function writeSitemap(string $path, string $xml): void
{
    $handle = fopen($path, 'c+b');

    if ($handle === false) {
        throw new RuntimeException('Could not open the sitemap for writing: ' . $path);
    }

    try {
        if (!flock($handle, LOCK_EX)) {
            throw new RuntimeException('Could not lock the sitemap for writing: ' . $path);
        }

        // Empty the old sitemap only after the complete replacement XML is ready.
        if (!ftruncate($handle, 0) || fseek($handle, 0) !== 0) {
            throw new RuntimeException('Could not empty the existing sitemap: ' . $path);
        }

        $length = strlen($xml);
        $written = 0;

        while ($written < $length) {
            $result = fwrite($handle, substr($xml, $written));

            if ($result === false || $result === 0) {
                throw new RuntimeException('Could not write the complete sitemap: ' . $path);
            }

            $written += $result;
        }

        fflush($handle);
        flock($handle, LOCK_UN);
    } finally {
        fclose($handle);
    }
}

function respond(string $message, bool $isError = false): void
{
    if (PHP_SAPI !== 'cli') {
        http_response_code($isError ? 500 : 200);
        header('Content-Type: text/plain; charset=UTF-8');
    }

    echo $message . PHP_EOL;
}
